language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
  - "node"
  - "8"
deploy:
  provider: heroku
  api_key:
    secure: "576b7ecf-88d9-4e4d-bbbf-e91d46d9fbb6"
  app: polar-island-17651
  on:
    repo: Yasherica0ne/cwp-34
before_script:
  - npm install